### ISSUE TITLE
Erreur lors du démarrage du composant

### ISSUE THREAD

**Issue by sebcaps** [saniho/apiFreeBox#2]
Bonjour avec la config suivante,
## System Health

version | core-2021.12.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.63-v7+
arch | armv7l
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4825
Installed Version | 1.16.0
Stage | running
Available Repositories | 996
Installed Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | pending

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 4
views | 6
mode | storage

</details>

j'ai l'erreur suivante lors du démarrage du composant 
```Logger: homeassistant.components.sensor
Source: custom_components/apiFreebox/freepybox.py:191
Integration: Capteur (documentation, issues)
First occurred: 19:09:09 (1 occurrences)
Last logged: 19:09:09

Error while setting up apiFreebox platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/apiFreebox/sensor.py", line 69, in setup_platform
    fbx.open(host, 80)
  File "/config/custom_components/apiFreebox/freepybox.py", line 79, in open
    self._access = self._get_freebox_access(host, port, self.api_version, self.token_file, self.app_desc, self.timeout)
  File "/config/custom_components/apiFreebox/freepybox.py", line 123, in _get_freebox_access
    app_token, track_id = self._get_app_token(base_url, app_desc, timeout)
  File "/config/custom_components/apiFreebox/freepybox.py", line 191, in _get_app_token
    resp = r.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
dans mon conf.yaml
```
- platform: apiFreebox
  host: mafreebox.free.fr
  scan_interval: 30
```

**Comment by saniho** [comment]
Hello, as-tu bien autorisé l'application sur mafreebox pour qu'elle puisse interroger le freeplayer ?

**Comment by sebcaps** [comment]
Désolé si j'ai loupé un truc, mais je pensais que l'autorisation se faisait au 1er démarrage => dans mon cas pas de demande de code sur la box.
J'ai tenté d'executer le script example.py mais en échec avec l'erreur 
```Traceback (most recent call last):
  File "/var/docker/homeassistant/custom_components/apiFreebox/freepybox.py", line 11, in <module>
    from . import exceptions
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 8, in <module>
    from freepybox import Freepybox
  File "/var/docker/homeassistant/custom_components/apiFreebox/freepybox.py", line 37, in <module>
    import fsnav
  File "/var/docker/homeassistant/custom_components/apiFreebox/fsnav.py", line 1, in <module>
    from . import fs
ImportError: attempted relative import with no known parent package```

**Comment by saniho** [comment]
Problème réglé
